steps:
  - label: 'Clone Duniverse'
    command:
      - cd /home/opam && rm -rf prep && mkdir -p prep && cd prep
      - opam install -y jbuilder
      - sudo apt-get -y install jq
      - git clone git://github.com/dra27/opam-compose /home/opam/prep/opam-compose
      - cd /home/opam/prep && bash -x ./opam-compose/prepare lwt
      - cd /home/opam/prep && jbuilder build
    agents:
      docker: "true"
    plugins:
      docker#v1.1.1:
        image: "ocaml/opam2-staging"
        always_pull: true
        environment:
          - OPAMYES=1
          - OPAMJOBS=12
