#!/bin/sh

cmd() {
    echo "\$ $@"
    $@
}

export OPAMERRLOGLEN=0
export OPAMYES=1

echo --- Installing external dependencies
starttime=`date +%s`
cmd opam depext -y $1 > $1.txt 2>&1
exitcode=$?
endtime=`date +%s`

# as a special case, raise exit 51 for a depext failure
if [ $exitcode -ne 0 ]; then
  echo '{}' >> $1.txt
  echo 51 $starttime $endtime >> $1.txt
  exit 0
fi

echo --- Installing opam package
cmd opam install --json $1.json -y -j 2 >> $1.txt 2>&1
exitcode=$?
endtime=`date +%s`
cat $1.json >> $1.txt
echo $exitcode $starttime $endtime >> $1.txt
cat $1.txt
exit 0
