#!/bin/sh

cmd() {
    echo "\$ $@"
    $@
}

export OPAMERRLOGLEN=0
export OPAMYES=1
starttime=`date +%s`
cmd opam depext -iyj 2 $1 > $1.txt 2>&1
exitcode=$?
endtime=`date +%s`
echo $exitcode $starttime $endtime >> $1.txt
cat $1.txt
exit 0
